# Generated by Django 5.1.7 on 2025-05-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="flight_image",
            field=models.ImageField(blank=True, null=True, upload_to="flights/"),
        ),
    ]
